### ISSUE TITLE
java.lang.reflect.InvocationTargetException on macos

### ISSUE THREAD

**Issue by jatinderbhola** [micwallace/WebPrint#17]
I have install following java version on my macOS.

```java -version
openjdk version "1.8.0_265"
OpenJDK Runtime Environment (Zulu 8.48.0.53-CA-macosx) (build 1.8.0_265-b11)
OpenJDK 64-Bit Server VM (Zulu 8.48.0.53-CA-macosx) (build 25.265-b11, mixed mode)```

Exception:
```Exception:

java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.install4j.runtime.installer.Installer.getScreenExecutor(Installer.java:105)
	at com.install4j.runtime.installer.Installer.runInProcess(Installer.java:58)
	at com.install4j.runtime.installer.Installer.main(Installer.java:46)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:65)
	at com.install4j.runtime.launcher.MacLauncher.main(MacLauncher.java:67)
Caused by: java.lang.reflect.InvocationTargetException
	at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1367)
	at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1342)
	at java.desktop/javax.swing.SwingUtilities.invokeAndWait(SwingUtilities.java:1480)
	at com.install4j.runtime.installer.Installer.getScreenExecutor(Installer.java:96)
	... 8 more
Caused by: java.lang.NoClassDefFoundError: com/apple/eawt/ApplicationListener
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at com.install4j.runtime.installer.frontend.WizardScreenExecutor.<init>(WizardScreenExecutor.java:49)
	at com.install4j.runtime.installer.frontend.InstallerWizardScreenExecutor.<init>(InstallerWizardScreenExecutor.java:18)
	at com.install4j.runtime.installer.Installer$2.run(Installer.java:99)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:303)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.ClassNotFoundException: com.apple.eawt.ApplicationListener
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 18 more```

Please let me know if you have any workaround. Thank you.

**Comment by micwallace** [comment]
Seems to be the installer launcher that is causing the issue. Maybe you can try run the .jar file directly? Or install oracle Java instead of openJDK?

On 30 October 2020 2:44:58 am AEDT, jatinder bhola <notifications@github.com> wrote:
>I have install following java version on my macOS.
>
>```java -version
>openjdk version "1.8.0_265"
>OpenJDK Runtime Environment (Zulu 8.48.0.53-CA-macosx) (build
>1.8.0_265-b11)
>OpenJDK 64-Bit Server VM (Zulu 8.48.0.53-CA-macosx) (build 25.265-b11,
>mixed mode)```
>
>Exception:
>```Exception:
>
>java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
>	at
>com.install4j.runtime.installer.Installer.getScreenExecutor(Installer.java:105)
>	at
>com.install4j.runtime.installer.Installer.runInProcess(Installer.java:58)
>	at com.install4j.runtime.installer.Installer.main(Installer.java:46)
>	at
>java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native
>Method)
>	at
>java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>	at
>java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
>	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:65)
>	at
>com.install4j.runtime.launcher.MacLauncher.main(MacLauncher.java:67)
>Caused by: java.lang.reflect.InvocationTargetException
>	at
>java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1367)
>	at
>java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1342)
>	at
>java.desktop/javax.swing.SwingUtilities.invokeAndWait(SwingUtilities.java:1480)
>	at
>com.install4j.runtime.installer.Installer.getScreenExecutor(Installer.java:96)
>	... 8 more
>Caused by: java.lang.NoClassDefFoundError:
>com/apple/eawt/ApplicationListener
>	at java.base/java.lang.Class.forName0(Native Method)
>	at java.base/java.lang.Class.forName(Class.java:315)
>	at
>com.install4j.runtime.installer.frontend.WizardScreenExecutor.<init>(WizardScreenExecutor.java:49)
>	at
>com.install4j.runtime.installer.frontend.InstallerWizardScreenExecutor.<init>(InstallerWizardScreenExecutor.java:18)
>	at com.install4j.runtime.installer.Installer$2.run(Installer.java:99)
>	at
>java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:303)
>	at
>java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
>	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
>	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
>	at java.base/java.security.AccessController.doPrivileged(Native
>Method)
>	at
>java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
>	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
>	at
>java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
>	at
>java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
>	at
>java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
>	at
>java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
>	at
>java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
>	at
>java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
>Caused by: java.lang.ClassNotFoundException:
>com.apple.eawt.ApplicationListener
>	at
>java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
>	at
>java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
>	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
>	... 18 more```
>
>Please let me know if you have any workaround. Thank you.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/micwallace/WebPrint/issues/17

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
